Repository TryItOn-TIO/TryItOn-frontend, pull requests merged in 2025-07, with the labels that each got.

#29 [refactor/product] API 연결 대비 구조로 리팩토링
  src/api/product.ts
  src/app/(home)/_components/HomeClient.tsx
  src/app/(home)/page.tsx
  src/app/category/[id]/_components/CategoryProductList.tsx
  src/app/category/[id]/layout.tsx
  src/app/category/[id]/page.tsx
  src/app/category/[id]/providers.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/common/AvatarWearInfo.tsx
  src/hooks/useInfiniteCategoryProducts.ts
  src/hooks/useIntersectionObserver.ts
  src/mock/categoryProducts.ts
  src/types/product.ts
Labels: 🔧 refactor

#38 [fix/product] 상품 카드 할인가 계산 로직 수정
  src/components/common/ProductCard.tsx
Labels: 🛠️ fix

#44 fix: zustand store persist 일괄 적용
  src/stores/google-token-store.ts
  src/stores/story-store.ts
Labels: 🛠️ fix

#47 [fix/product-detail] 유사한 상품 목록 조회 API 연결 / style 일부 수정
  src/api/productDetail.ts
  src/app/cart/page.tsx
  src/app/detail/[id]/_components/DetailClient.tsx
  src/app/detail/[id]/_components/DetailRecommand.tsx
  src/app/mypage/address/page.tsx
  src/app/mypage/orders/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/order/page.tsx
  src/components/ui/SimpleProductCard.tsx
  src/types/product.ts
Labels: 🔮 feat

#50 [fix/tryon] try on 전역 상태 타입을 response DTO에 맞춰 수정
  src/api/avatar.ts
  src/app/(home)/_components/CategoryProductList.tsx
  src/app/(home)/_components/HomeClient.tsx
  src/app/(home)/page.tsx
  src/app/category/[id]/_components/CategoryAvatarClient.tsx
  src/app/detail/[id]/_components/DetailMainImg.tsx
  src/components/common/AvatarWearInfo.tsx
  src/components/common/DefaultAvatarSlot.tsx
  src/components/common/ProductCard.tsx
  src/components/ui/AvatarModal.tsx
  src/hooks/useAvatarTryon.ts
  src/stores/avatar-store.ts
  src/types/avatar.ts
Labels: 🛠️ fix

#51 fix: 전역 상태 타입 변경에 따른 수정
  src/app/category/[id]/_components/CategoryAvatarClient.tsx
  src/components/common/AvatarWearInfo.tsx
Labels: 🛠️ fix

#53 [feat/closet] 옷장에 스토리 공유, 친구와 함께 고르기 추가
  src/api/index.ts
  src/app/closet/_components/SavedOutfitCard.tsx
  src/app/closet/_components/SavedOutfitsSection.tsx
  src/app/closet/_components/WishlistSection.tsx
  src/app/story/[id]/_components/ClothesInfo.tsx
  src/app/story/[id]/_components/StoryImage.tsx
  src/app/story/[id]/_components/comment/CommentSection.tsx
  src/app/story/[id]/hooks/useCommentInteraction.ts
  src/app/story/create/_hooks/useAvatarData.ts
  src/app/story/create/page.tsx
  src/app/tryon-room/page.tsx
  src/components/common/ProductCard.tsx
  src/components/common/icons.tsx
  src/components/ui/ProductActionCard.tsx
  src/hooks/useWishlist.ts
Labels: 🔮 feat

#54 [feat/search] 헤더 검색 기능 구현
  src/api/search.ts
  src/app/search/_components/SearchPageClient.tsx
  src/app/search/_components/SearchResults.tsx
  src/app/search/page.tsx
  src/components/common/SearchInput.tsx
  src/components/layout/Header.tsx
  src/hooks/useDebounce.ts
  src/types/product.ts
Labels: 🔮 feat

#55 [style] 전역 Scroll-to-Top 기능 구현
  src/app/layout.tsx
  src/components/common/ScrollToTop.tsx
Labels: 🎨 style

#58 [feat/main] 메인페이지 제품 정보 변경 및 스토리 섹션 추가
  src/app/(home)/_components/CategoryProductList.tsx
  src/app/(home)/_components/HomeClient.tsx
  src/app/(home)/page.tsx
  src/app/detail/[id]/_components/DetailRecommand.tsx
  src/app/story/_components/StoryCard.tsx
  src/app/story/page.tsx
Labels: 🔮 feat

#59 [fix/story] 스토리 swiper 깨지는 현상을 해결하기 위해 css로 변경
  src/app/(home)/_components/CategoryProductList.tsx
Labels: 🛠️ fix

#65 [fix/home, signin] 서버 컴포넌트와 클라이언트 컴포넌트 분리
  src/app/(home)/_components/HomeClientWrapper.tsx
  src/app/(home)/page.tsx
  src/app/signin/_components/SigninClient.tsx
  src/app/signin/page.tsx
Labels: 🛠️ fix

#66 [Fix/build error] 빌드 에러 잡기
  src/app/fail/FailClient.tsx
  src/app/fail/page.tsx
  src/app/signup/_components/SignupClient.tsx
  src/app/signup/page.tsx
  src/app/tryon-room/_components/.gitkeep
  src/app/tryon-room/_components/TryonRoomClient.tsx
  src/app/tryon-room/page.tsx
  src/components/layout/Header.tsx
Labels: 🛠️ fix

#67 [refactor/search] 상품 검색 결과 무한 스크롤 적용
  src/api/search.ts
  src/app/search/_components/SearchPageClient.tsx
  src/app/search/_components/SearchResults.tsx
  src/hooks/useInfiniteSearchProducts.ts
Labels: 🔧 refactor

#70 [style/avatar_modal] 로그인 여부에 따라 아바타 모달 접근 제어 및 UI 개선
  src/app/detail/[id]/_components/DetailMainImg.tsx
  src/components/layout/Header.tsx
  src/components/ui/AvatarModal.tsx
Labels: 🎨 style

#71 [feat/alarm] 데스크탑(PC)과 모바일에 맞춰 알림 위치와 모달 표시
  src/app/detail/[id]/_components/DetailClient.tsx
  src/app/detail/[id]/_components/DetailMainImg.tsx
  src/components/common/ProductCard.tsx
  src/components/layout/Header.tsx
  src/components/ui/AvatarModal.tsx
  src/components/ui/Modal.tsx
  src/components/ui/TryOnResultModal.tsx
  src/hooks/useAvatarTryon.ts
  src/hooks/useMediaQuery.ts
  src/stores/try-on-store.ts
Labels: 🔮 feat, 🎨 style

#74 [feat/recommend] 개인화 추천, 인기상품, 연령대별 인기상품, 유사상품 API 연결
  src/api/recommend.ts
  src/app/(home)/_components/HomeClient.tsx
  src/app/(home)/_components/HomeClientWrapper.tsx
  src/app/(home)/_components/MainProductList.tsx
  src/app/detail/[id]/_components/DetailRecommand.tsx
  src/components/HeroSection.tsx
  src/types/product.ts
Labels: 🔮 feat

#78 feat: 비회원 메인페이지 아바타 적용
  public/images/home/.gitkeep
  public/images/home/aa.webp
  public/images/home/ab.webp
  public/images/home/ac.webp
  public/images/home/ba.webp
  public/images/home/bb.webp
  public/images/home/bc.webp
  public/images/home/bottom-a.jpg
  public/images/home/bottom-b.jpg
  public/images/home/bottom-c.webp
  public/images/home/ca.webp
  public/images/home/cb.webp
  public/images/home/cc.webp
  public/images/home/top-a.webp
  public/images/home/top-b.webp
  public/images/home/top-c.webp
  src/components/AvatarPreview.tsx
  src/components/HeroSection.tsx
Labels: 🎨 style

#79 [Style/closet_page] 옷장 페이지 개선
  public/images/common/bookmark.svg
  public/images/common/bookmark_filled.svg
  public/images/common/mypage.svg
  src/api/wishlist.ts
  src/app/closet/_components/CategoryFilter.tsx
  src/app/closet/_components/ClosetProductSection.tsx
  src/app/closet/_components/SavedOutfitCard.tsx
  src/app/closet/_components/SavedOutfitsSection.tsx
  src/app/closet/_components/WishlistSection.tsx
  src/app/closet/page-test.tsx
  src/app/closet/page.tsx
  src/app/rooms/[inviteCode]/page.tsx
  src/app/rooms/page.tsx
  src/app/tryon-room/_components/TryonRoomClient.tsx
  src/app/tryon-room/page.tsx
Labels: 🔮 feat, 🎨 style

#80 style: 회원가입 버튼 색 변경
  src/components/HeroSection.tsx
Labels: 🎨 style

#83 [fix/category] 세부 카테고리 조회 기능 추가
  src/app/category/[id]/_components/CategoryClient.tsx
  src/constants/category.ts
Labels: 🔮 feat

#84 [style/header]: 헤더 UI 스타일 변경
  src/components/layout/Header.tsx
Labels: 🎨 style

#88 [fix/qa] QA 내용 반영
  src/api/story.ts
  src/app/(home)/_components/CategoryProductList.tsx
  src/app/(home)/_components/HomeClientWrapper.tsx
  src/app/(home)/_components/MainProductList.tsx
  src/app/(home)/page.tsx
  src/app/cart/page.tsx
  src/app/closet/_components/SavedOutfitCard.tsx
  src/app/closet/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/settings/page.tsx
  src/app/mypage/story/_components/DeletableStoryCard.tsx
  src/app/mypage/story/_components/MyStoryGrid.tsx
  src/app/mypage/story/_components/StorySortButtons.tsx
  src/app/mypage/story/page.tsx
  src/app/signin/_components/SigninForm.tsx
  src/app/signup/_components/SendVerification.tsx
  src/app/signup/_components/SignupClient.tsx
  src/app/signup/oauth/page.tsx
  src/app/story/_components/StoryCard.tsx
  src/app/story/_components/StoryEmptyState.tsx
  src/app/story/_components/StoryGrid.tsx
  src/app/story/page.tsx
  src/components/HeroSection.tsx
  src/components/common/Spinner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 🛠️ fix, 🔧 refactor

#89 [fix/qa] 메인페이지 스토리 추가 및 헤더 수정
  src/app/(home)/_components/CategoryProductList.tsx
  src/app/(home)/_components/HomeClientWrapper.tsx
  src/app/(home)/_components/MainProductList.tsx
  src/app/story/page.tsx
  src/components/layout/Header.tsx
Labels: 🛠️ fix, 🎨 style

#96 [fix/qa] 모바일 비로그인 유저 tryon 아이콘 삭제
  src/app/success/page.tsx
  src/components/layout/Header.tsx
Labels: 🎨 style

#97 [Fix/Virtual Fitting Modal] 가상 피팅 모달 기능 개선
  src/components/layout/Header.tsx
  src/components/ui/TryOnResultModal.tsx
Labels: 🛠️ fix, 🎨 style

#101 [fix/qa] 포스트잇 디자인 변경 및 일부 에러 수정
  src/app/detail/[id]/_components/DetailMainImg.tsx
  src/app/detail/[id]/_components/DetailOrderOptions.tsx
  src/app/signin/_components/SigninForm.tsx
  src/app/story/[id]/_components/comment/Comment.tsx
  src/app/story/[id]/_components/controller/MenuBar.tsx
  src/app/story/[id]/_components/controller/StoryControlBar.tsx
  src/app/story/_components/StoryHeader.tsx
  src/components/ui/CustomAlert.tsx
Labels: 🔮 feat, 🛠️ fix

#102 [fix/qa] 장바구니 페이지 UI 에러 수정
  src/app/detail/[id]/_components/DetailClient.tsx
  src/app/detail/[id]/_components/DetailUserForm.tsx
  src/hooks/useCart.ts
Labels: 🛠️ fix

#105 fix: 개인화 추천 상품 응답에 따라 섹션 노출 #81
  src/app/(home)/_components/MainProductList.tsx
Labels: 🛠️ fix
